# Generated by Django 4.1.6 on 2023-02-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.IntegerField(default=0)),
                ('current_mileage', models.IntegerField(default=0)),
            ],
        ),
    ]
