# Generated by Django 4.1.5 on 2023-02-21 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mileage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='current_mileage',
        ),
        migrations.AddField(
            model_name='mileage',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
