# Generated by Django 4.1.5 on 2023-02-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0002_remove_mileage_current_mileage_mileage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='user',
        ),
    ]
