# Generated by Django 4.1.7 on 2023-02-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mileage',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
