# Generated by Django 4.1.5 on 2023-02-21 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmission',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='mileage_reward',
            field=models.PositiveIntegerField(),
        ),
    ]
