# Generated by Django 4.1.7 on 2023-02-20 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='mileage_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
