# Generated by Django 4.1.5 on 2023-02-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mission', '0002_completedmission_user_alter_mission_mileage_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedmission',
            name='user',
        ),
    ]
